services:
  dev:
    container_name: atma17
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '64gb'
    volumes:
      - type: bind
        source: $PWD
        target: /workspace
      - type: volume
        source: venv
        target: /workspace/.venv
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    tty: true

volumes:
  venv:
