params:
  model_path: microsoft/deberta-v3-large
  metric: auc
  target_col_class_num: 2
  max_length: 192
  fp16: True
  learning_rate: 2e-5
  epochs: 2
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 32
  steps: 50
  lr_scheduler_type: cosine
  weight_decay: 0.01
